! -------------------------------------------------------------------------
!
!                      OWI generator
!                 subroutine of genOWI.F90
!                  Part of Multistage tool
!
! --------------------------------------------------------------------------
! SYNTAX:
!       ./genOWI.x [number of gefs ensemble runs]
!
! Functions:
! (0) reads u.srtd.csv and v.srtd.csv generated by download_fegs_data.sh:
! function remove_duplicate
! (1) Remove duplicates that were not recognized by the 
! sort and uniq commands.
! Explanation:
!    GEFS should have the same value at the sahred corners of
!    two neighboring cells.
!    One cell may assign, for example, 2 m/s while 
!    neighboring cell assigns 2.0001 m/s
!    That's why it is not detected as duplicate.
!
! (2) Organize data points
! (3) calculate the average and std 
! (4) Create 1st wind forcing from the ave.
!     2nd and 3rd forcings are generated from +-std
! ---------------------------------------------------------------------------

  program genOWI
  implicit none
!
  character(len=30)    :: filename
  character(len=20)    :: output_name
  character(len=100)   :: arg
  character(len=15)    :: starttime, endtime
  character(len=5)     :: stat
  integer              :: unt
  integer              :: cnt
  integer              :: n, io
  integer              :: i,j,k
  integer              :: i1, i2, i3
  integer              :: ensemble_num
  integer              :: freq, windForcing
  integer              :: num_cell_corners
  integer              :: output_snap_num
  integer              :: temp_freq
!
  character(len=15)    :: lCYMDH
  real                 :: dx, dy
  real                 :: swlong,swlat
  integer              :: ilat, ilon 
!
  real, dimension(10000000,9)    :: tmp          ! have this or allocate option
  real, dimension(10000000,12)   :: ave_std
!
! Getting arguments: for now the number of ensemble runs
  do k=1, iargc()
     call  getarg(k,arg)
     if ( k.eq.1 ) then
        read (arg,'(i10)') ensemble_num
     elseif ( k.eq.2 ) then
        read (arg,'(A15)') starttime
     elseif ( k.eq.3 ) then
        read (arg,'(A15)') endtime
     else
        read (arg,'(i5)') temp_freq
     endif
  enddo

! Formatting u 
  filename='u.no_header.srtd.csv'
  unt=90
  i1=1
  i2=2
  i3=3
  tmp = remove_duplicate(filename, unt, i1,i2,i3)

! Formatting v
  filename='v.no_header.srtd.csv'
  unt=91
  i1=4
  i2=5
  i3=6
  tmp =  remove_duplicate(filename, unt, i1,i2,i3)
 
! Formatting v
  filename='press.no_header.srtd.csv'
  unt=91
  i1=7
  i2=8
  i3=9
  tmp =  remove_duplicate(filename, unt, i1,i2,i3)

! Calling subroutine to calculate the number of cell points 
! and the number of output time snaps
  call points_timesnap_size(tmp, ensemble_num, num_cell_corners,output_snap_num)

! Writing to a file for checking the veracity of procedue, for further
! investigating and troubleshooting
  do k=1,ensemble_num*num_cell_corners*output_snap_num
     write(92,*) tmp(k,1:9)
  enddo

! Taking average of Us and Vs and standard deviation
! Format of table (fort.93):
! -------------------------------------------------------------------------------------------------------------------------------------------
! U_mean | V_mean |  P_mean | std_u | std_v | std_p | U_mean+std_u | V_mean+std_v | P_mean+std_p | U_mean-std_u | V_mean-std_v | P_mean-std_p
!   ...  |   ...  |   ...   |   ... |  ...  |  ...  |      ...     |      ...     |      ...     |      ...     |      ...     |      ...  
! -------------------------------------------------------------------------------------------------------------------------------------------
  ave_std = Mean_std(tmp, ensemble_num, num_cell_corners,output_snap_num)
 
! Writing to a file for checking the veracity of procedue
  do k=1,output_snap_num*num_cell_corners
     write(93,*) ave_std(k,1:12)
  enddo

! Grab the iLat and iLon (subroutine)
  call header_fort222(tmp, num_cell_corners, iLon, iLat, dx, dy, swlat, swlong)

! Call the wind forcing writing subroutine
  call writer_WindPress(starttime, endtime, num_cell_corners, output_snap_num, iLat,iLon,dx,dy,swlat,swlong,ave_std,temp_freq,stat)


!                     F U N C T I O N S
! ##############################################################
!                    Removing duplicates
! ##############################################################
!
  contains
  function remove_duplicate(filename,unt,i1,i2,i3)
! 
  character(len=30)          :: filename
  integer                    :: i1, i2, i3
! real, allocatable, dimension(:,:) :: remove_duplicate ! This overwrite first
! call which is the u component
  real, dimension(10000000,9) :: remove_duplicate
  real                       :: comp
  real                 :: LON, LAT
  real                 :: LON_0, LAT_0
  real                 :: diffLat, diffLon
  integer              :: io
  integer              :: k
  integer              :: n
  integer              :: unt
!
  open(unit=unt,file=filename)
!
! Reading initial
  read(unt,*)  LON, LAT, comp
  remove_duplicate(1,i1) = LON
  remove_duplicate(1,i2) = LAT
  remove_duplicate(1,i3) = comp
!
  io = 0.0
  k  = 2
  do
  if ( io.eq.0 ) then
!    Initials
!    LON_0 = LON
!    LAT_0 = LAT
     read(unt,*,iostat=io) LON, LAT, comp
!    diffLon = abs(LON - LON_0)
!    diffLat = abs(LAT - LAT_0)
!    if (( diffLon.eq.0 ) .and. ( diffLat.eq.0 )) then
!         write(*,*) 'Duplicate found for', comp, 'component of velocity' , LON, LAT, comp
!    else
          remove_duplicate(k,i1) = LON
          remove_duplicate(k,i2) = LAT
          remove_duplicate(k,i3) = comp
          k = k + 1
!    endif
  else
     go to 13
  endif
!
  enddo
13 continue
!
  end function                    
! 

! ##############################################################
!                  Calculating mean and std 
! ##############################################################
!
  function Mean_std(tmp, ensemble_num, num_cell_corners,output_snap_num)
!
  real, dimension(10000000,9)  :: tmp
  integer                     :: ensemble_num   
  integer                     :: i
  integer                     :: num_cell_corners
  integer                     :: length_tmp
  integer                     :: output_snap_num
  integer                     :: hr
  integer                     :: h
  integer                     :: j
  integer                     :: ens_num
  real                        :: sumU , sumV, sumP
  real                        :: stdU2, stdV2, stdP2
  real                        :: stdU , stdV, stdP
  real,dimension(10000000,12)   :: Mean_std
!
! Structure
! mean_u   mean_v  mean_P  std_u  std_v  std_p  mean_u+std_u  mean_u+std_v  mean_p+std_p  mean_u-std_u  mean_u-std_v  mean_p-std_p

!
! Calculating the average of wind speed at each point and
! at each time step over 21 ensemble members
  do i=1,num_cell_corners*output_snap_num
     sumU = 0 
     sumV = 0
     sumP = 0
     do j=1,ensemble_num
        sumU = sumU + tmp(i+(j-1)*num_cell_corners*output_snap_num , 3 )
        sumV = sumV + tmp(i+(j-1)*num_cell_corners*output_snap_num , 6 )
        sumP = sumP + tmp(i+(j-1)*num_cell_corners*output_snap_num , 9 )
     enddo
     Mean_std (i,1) = sumU/ensemble_num
     Mean_std (i,2) = sumV/ensemble_num
     Mean_std (i,3) = sumP/ensemble_num
  enddo
!
! Calculating standard deviation
  do i=1,num_cell_corners*output_snap_num
     stdU2=0
     stdV2=0
     stdP2=0
     do j=1,ensemble_num
        stdU2=stdU2 + (tmp(i+(j-1)*num_cell_corners*output_snap_num,3) - Mean_std(i,1))**2
        stdV2=stdV2 + (tmp(i+(j-1)*num_cell_corners*output_snap_num,6) - Mean_std(i,2))**2
        stdP2=stdP2 + (tmp(i+(j-1)*num_cell_corners*output_snap_num,9) - Mean_std(i,3))**2
     enddo
     Mean_std (i,4) = sqrt(stdU2/(ensemble_num-1))
     Mean_std (i,5) = sqrt(stdV2/(ensemble_num-1))
     Mean_std (i,6) = sqrt(stdP2/(ensemble_num-1))
  enddo
!
! Calculating the ave+std 
  Mean_std (:,7) = Mean_std (:,1) + Mean_std (:,4)
  Mean_std (:,8) = Mean_std (:,2) + Mean_std (:,5) 
  Mean_std (:,9) = Mean_std (:,3) + Mean_std (:,6)
!
! Calculating the ave-std 
  Mean_std (:,10) = Mean_std (:,1) - Mean_std (:,4)
  Mean_std (:,11) = Mean_std (:,2) - Mean_std (:,5) 
  Mean_std (:,12) = Mean_std (:,3) - Mean_std (:,6)
!
  end function  
!
! ##############################################################
!       Writing fort.222 from mean and std UV (ave_std)
! ##############################################################
!
!               E N D    O F    F U N C T I O N S 
! ##############################################################
  end program genOWI
