! -------------------------------------------------------------------------
!
!                          Generating mean/+std/-std of 
!                    fort.221/2 generated from NMB produxts
!                          provided as SREF products
! -------------------------------------------------------------------------
!
! Author: Peyman Taeb, Dec 2018
!
! ------------------------------------------------------------------------
!
  program genFORTS
  implicit none
  
  ! Variables initialization and declarations
  character(len=150)    :: arg
  character(len=15 )    :: type_file 
  !
  character(len=150)    :: ctl_press, p1_press, p2_press, p3_press,p4_press
  character(len=150)    :: p5_press, p6_press, n1_press, n2_press
  character(len=150)    :: n3_press, n4_press, n5_press, n6_press
  character(len=150)    :: ctl_wind , p1_wind , p2_wind , p3_wind,p4_wind 
  character(len=150)    :: p5_wind , p6_wind , n1_wind , n2_wind 
  character(len=150)    :: n3_wind , n4_wind , n5_wind , n6_wind
  character(len=150), dimension(:), allocatable  ::  files
  character(len=80)     :: line1
  character(len=80)     :: header
  character(len=10)     :: fmt
  !
  integer               :: k
  integer               :: i,ii,j, unt, n
  integer               :: b
  integer               :: TS
  integer               :: l,m
  integer               :: P
  integer               :: u1_in, u2_in, u1_o, u2_o
  integer,dimension(2)  :: points
  !
  real                  :: c1,c2,c3,c4,c5,c6,c7,c8
  real                  :: std
  real                  :: summ
  !
  real, dimension(:,:),allocatable   :: c_array
  real, dimension(:,:),allocatable   :: c_mean,meanPstd,meanMstd
  real, dimension(:,:),allocatable   :: stdd
 
  ! ----------------------------------------------------------
  !
  !                     Main body
  
  ! Allocating a character type array including all members
  allocate(files(26))

  ! Constructing a character type array including all members
  files(1) = 'ctl_press'
  files(2) = 'n1_press'
  files(3) = 'n2_press'
  files(4) = 'n3_press'
  files(5) = 'n4_press'
  files(6) = 'n5_press'
  files(7) = 'n6_press'
  files(8) = 'p1_press'
  files(9) = 'p2_press'
  files(10) = 'p3_press'
  files(11) = 'p4_press'
  files(12) = 'p5_press'
  files(13) = 'p6_press'
  files(14) = 'ctl_wind' 
  files(15) = 'n1_wind' 
  files(16) = 'n2_wind' 
  files(17) = 'n3_wind' 
  files(18) = 'n4_wind' 
  files(19) = 'n5_wind' 
  files(20) = 'n6_wind' 
  files(21) = 'p1_wind' 
  files(22) = 'p2_wind' 
  files(23) = 'p3_wind' 
  files(24) = 'p4_wind' 
  files(25) = 'p5_wind'
  files(26) = 'p6_wind'  

  ! Passing fort.221 and fort.222 generated by NAMtoOWI.pl
   do k=1, iargc()
     call  getarg(k,arg)
     ! read in 
     read (arg,'(A150)') files(k)
     ! open
     open(unit=k+9,file=files(k))
  enddo
  
  ! Free up some memory
  deallocate(files)

  ! Open the file for writing statistical press and wind
  !!! Pressure
  open(80, file="sref_mean.221", position="append", action="write")
  open(81, file="sref_Pstd.221", position="append", action="write")
  open(82, file="sref_Mstd.221", position="append", action="write")
  !!! Wind        
  open(83, file="sref_mean.222", position="append", action="write")
  open(84, file="sref_Pstd.222", position="append", action="write")
  open(85, file="sref_Mstd.222", position="append", action="write")

  ! Reading the 1st line of all files
  do unt=10,35
     read(unt,'(A80)') line1
  enddo

  ! Writing the header to new wind/press files
  do b=80,85
     write(b,'(A80)') line1 
  enddo
  
  ! There are 3200 lines of 8 pressures components (points=3200)
  ! There are 3200 lines of U-comps and 3200 of V-comps (points=6400)
  points(1) = 3200
  points(2) = 6400
  
  ! There are 29 time step (3.5 days)
  do P=1,2  

     ! Construct pressure files first, and then wind files
     do TS=1,29

     ! Ok, what we are doing now
     if ( P.eq.1) then
        type_file='pressure field'
     else
        type_file='wind field'
     endif
     write(*,*) "Start constructing ", type_file, "input forcing files. &
&                Time step is ", TS," out of 29"


111    format (8f10.4)
112    format (8f3.6)
 
     ! Defining variables that handle distinguishing wind and press
     ! Units for Pressure (U) members 10-22
     ! Units for winde (U)  members 23-35
     if ( P.eq.1 ) then
        ! format
        fmt='(8f10.4)'
        ! inputs
        u1_in=10
        u2_in=22
        ! outputs
        u1_o=80
        u2_o=82
     else
        ! format
        fmt='(8f10.6)'
        u1_in=23
        u2_in=35
        ! outputs
        u1_o=83
        u2_o=85
     endif

     ! Reading the headers of members
     do unt=u1_in,u2_in
        read(unt,'(A80)') header 
     enddo

     ! Writing the header to new wind/press files
     do b=u1_o,u2_o
        write(b,'(A80)') header
     enddo

     ! Go through buddy
     do i=1,points(P) 

        ! Allocating, really?
        allocate(c_array(13,8))
        allocate(c_mean(1,8))
        allocate(stdd(1,8))
        allocate(meanPstd(1,8))
        allocate(meanMstd(1,8))
     
       ! There are 8 components in each line
       k=1

       do unt= u1_in,u2_in
          read(unt,fmt) c1, c2, c3, c4, c5, c6, c7, c8
          c_array (k,1) = c1
          c_array (k,2) = c2
          c_array (k,3) = c3
          c_array (k,4) = c4
          c_array (k,5) = c5
          c_array (k,6) = c6
          c_array (k,7) = c7
          c_array (k,8) = c8
          k=k+1
       enddo
     
       ! Do the statistic
       ! number of ensemble 13
       do n=1,8
          summ=0
          do j=1,13
             summ = summ + c_array(j,n)
          enddo
          c_mean (1,n) = summ/13
       enddo
     
       ! Calculating STD
       do m=1,8   ! through 8 components in each line
          std = 0
          do l=1,13   ! through all ensembles
             std = std + ( c_array(l,m) - c_mean(m,1) )**2
          enddo
          stdd (1,m) = sqrt(std/12) 
          meanPstd(1,m) = c_mean (1,m)+stdd (1,m)
          meanMstd(1,m) = c_mean (1,m)-stdd (1,m)
       enddo

       ! writing for pressure
       if ( P.eq.1 ) then
          write(80,fmt) ((c_mean(ii,j),ii=1,1),j=1,8)
          write(81,fmt) ((meanPstd(ii,j),ii=1,1),j=1,8) 
          write(82,fmt) ((meanMstd(ii,j),ii=1,1),j=1,8)
       else
          write(83,fmt) ((c_mean(ii,j),ii=1,1),j=1,8)
          write(84,fmt) ((meanPstd(ii,j),ii=1,1),j=1,8)
          write(85,fmt) ((meanMstd(ii,j),ii=1,1),j=1,8)
       endif
  
       ! Free the memory and allow for re-allocation  
       deallocate(c_array)
       deallocate(c_mean)
       deallocate(stdd)
       deallocate(meanPstd)
       deallocate(meanMstd)
 
       enddo ! Over nodes in each time step
     enddo ! over time step
  enddo ! over generating press and wind
  end program
