! -------------------------------------------------------------------------
!
!                 USGS water level process
!     For validating model results using USGS observations
!                  Part of Multistage tool
!
! --------------------------------------------------------------------------
! SYNTAX:
!       ./usgs_wl_process.F90 <trimmed USGS file name> <SSHAG>
!
! Functions:
! (1) Read gage depth from the trimmed file generated by
! the bash script that downloads data and calculate the average
! (2) demean data to obtain the surface elevations.
! (3) Converting surface elevation in feet to meter    
! (4) Applying sea surface height above goid.
! ---------------------------------------------------------------------------
  program usgs_wl_process
  implicit none
   
  character(len=120)        :: arg
  character(len=50)         :: filename
  character(len=100)        :: junk
  character(len=20)         :: junk1, junk2, junk3, junk4, junk5, junk6
  real                      :: sshag
  real                      :: summation
  real                      :: mean
  integer                   :: io
  integer                   :: k
  integer                   :: cntr
  real                      :: depth
  real, dimension(:,:), allocatable  :: raw_depth
  real, dimension(:,:), allocatable  :: demean
  real, dimension(:,:), allocatable  :: cnvrt_demean
  real, dimension(:,:), allocatable  :: sshag_cnvrt_demean
 
  ! Getting arguments: for now the number of ensemble runs
  do k=1, iargc()
     call  getarg(k,arg)
     if ( k.eq.1 ) then
        read (arg,'(A50)') filename    
     elseif ( k.eq.2 ) then
        read (arg,*) sshag    
     endif
  enddo

  ! Openning the file                 
  open(unit=70, file=filename)

  ! Allocating
  ! (1) finding the dimension
  io=0.0
  cntr=0
  do
    if ( io.eq.0 ) then
       read (70,*,iostat=io) 
       cntr=cntr+1
    else
       go to 20 
    endif
  enddo

20 continue 

  ! Closing file
  close(70)

  ! Openning again for allocating
  open(unit=70, file=filename)

  ! (2) Assigning
  allocate(raw_depth(cntr,1)) 

  ! Reading and assigning
  do k=1,cntr-1
     read (70,*) junk1, junk2, junk3, junk4, junk5, depth, junk6
     raw_depth(k,1)=depth
  enddo

  ! Taking average
  summation=sum(raw_depth)
  mean=summation/(cntr-1)
  
  ! Demean
  allocate(demean(cntr,1))
  do k=1,cntr-1
     demean(k,1)=raw_depth(k,1)-mean
  enddo
  
  ! Converting feet to meter
  allocate(cnvrt_demean(cntr,1))
  do k=1,cntr-1
     cnvrt_demean(k,1)=demean(k,1)*0.3048
  enddo

  ! Applying SSHAG
  allocate(sshag_cnvrt_demean(cntr,1))
  do k=1,cntr-1
     sshag_cnvrt_demean(k,1)=cnvrt_demean(k,1)+sshag
  enddo
  
  ! Writing to file
  do k=1,cntr-1
     write(71,'(f10.6)') sshag_cnvrt_demean(k,1)
  enddo
  end program
